services:
  pveowo:
    image: neomediatech/pve:latest
    #build: ./minecraft-docker
    #command: ["java", "-Xmx2048M", "-jar", "server.jar", "true"]
    privileged: true
    env_file:
      - .env
    devices:
      - "/dev/kvm"
      - "/dev/fuse"
        #OPTIONS="$OPTIONS --privileged --device /dev/fuse --device=/dev/kvm --add-host $NAME:127.0.0.1"
    extra_hosts:
      - "pveowo:127.0.0.1"
    volumes:
      - "./data:/root/minecraft"
      - "./data/logs:/var/log"
      - "./data/pve_cluster:/var/lib/pve-cluster"
      - "./data/pve_manager:/var/lib/pve-manager"
      - "./data/bin:/srv/bin"
    ports:
      - "8006:8006"
    restart: always
