networks:
  netvm:
    external: true
    name: netvm

services:
  pve-server2:
    image: pve-custom2
    build: ./pve
    container_name: pve-server2
    privileged: true
    hostname: pve-owo
    networks:
      netvm:
        ipv4_address: 192.168.12.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "./data/logs:/var/log"
      - "./data/pve/pve_cluster:/var/lib/pve-cluster"
      - "./data/pve/pve_manager:/var/lib/pve-manager"
      - "./data/bin:/srv/bin"
      - "./data/disks:/var/lib/vz"
      - "./data/network/interfaces:/etc/network/interfaces"
      - "./data/network/dhcp/conf:/etc/dhcp"
      - "./data/network/dhcp/dhcpd.leases:/var/lib/dhcp/dhcpd.leases"
      - "./data/network/dhcp/int:/etc/default/isc-dhcp-server"
      - "/etc/resolv.conf:/etc/resolv.conf"
    restart: unless-stopped
