networks:
  netvm:
    external: true
    name: netvm

services:
  socat-server:
    image: socat-custom
    build: ./sc 
    container_name: socat-server
    privileged: true
    networks:
      netvm:
        ipv4_address: 192.168.12.3
    ports:
      - 8006:8006
      - 8007:8007
      - 2222:2222
    volumes:
      - "./data/socat.sh:/root/socat.sh"
    restart: unless-stopped
